[package]
name = "riscv-helloworld"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"